name: web - CI
on:
  push:
    branches: ["main"]
  merge_group:

jobs:
  build:
    uses: ./.github/workflows/web-build.yml
    with:
      environment: dev
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/web-deploy.yml
    with:
      environment: dev
    secrets: inherit
