name: Web - CI/CD

on:
  push:
    branches: ["main"]
  merge_group:

jobs:
  web-deploy:
    uses: kutruff/fly-t3-turbo/.github/workflows/web-deploy.yml@main
    with:
      environment: dev
      # concurrency: dev
    secrets: inherit
