name: web - CI
on:
  push:
    branches: ["main"]
  merge_group:

jobs:
  build:
    uses: kutruff/fly-t3-turbo/.github/workflows/web-build.yml@main
    with:
      environment: dev
    secrets: inherit
  deploy:
    needs: build
    uses: kutruff/fly-t3-turbo/.github/workflows/web-deploy.yml@main
    with:
      environment: dev
    secrets: inherit
